#!/bin/sh

export GIT_WORK_TREE=/

case "$1" in
  autocommit)
    shift

    do_push=false
    while getopts ":p" opt; do
      case "$opt" in
        p) do_push=true ;;
      esac
    done

    git status --porcelain | grep -v '^??' || exit 0
    git commit -a -m 'autocommit' || exit $?
    if $do_push; then
      git push
    fi
  ;;

  initbranch)
    shift
    branch="$1"
    gitdir="$(git rev-parse --git-dir)"
    git symbolic-ref HEAD "refs/heads/$branch"
    git config "branch.$branch.remote" origin
    git config "branch.$branch.merge" "refs/heads/$branch"
    
    if test -f "$gitdir/refs/heads/$branch"
    then
      git reset --mixed
    else
      rm "$gitdir/index"
    fi
    
    exit 0
  ;;
  *)
    exec git $@
  ;;
esac
